version: "3.8"

services:
  backend:
    build: ./dogfinder-backend
    volumes:
      - ./backend/uploads:/app/uploads
      - ./model:/app/model
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: ./dogfinder-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:8000
    depends_on:
      - backend
